# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/MicroSerivces__EcommerceWeb/backend/apigateway" # Location of package manifests
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/MicroSerivces__EcommerceWeb/backend/checkoutservice" # Location of package manifests
    schedule:
      interval: "weekly"    
      
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/MicroSerivces__EcommerceWeb/backend/configservice" # Location of package manifests
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/MicroSerivces__EcommerceWeb/backend/discoveryservice" # Location of package manifests
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/MicroSerivces__EcommerceWeb/backend/orderservice" # Location of package manifests
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/MicroSerivces__EcommerceWeb/backend/paymentservice" # Location of package manifests
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/MicroSerivces__EcommerceWeb/backend/productservice" # Location of package manifests
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/MicroSerivces__EcommerceWeb/backend/userservice" # Location of package manifests
    schedule:
      interval: "weekly"  
